# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: atcli
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure -vendor-only 
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  targets:
    - "darwin_amd64"
    - "windows_amd64"
    - "windows_386"
    - "linux_amd64"
    - "linux_386"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
