name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
      GOFLAGS: -mod=vendor
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        # export PATH=$PATH:$(go env GOPATH)/bin
        go mod vendor
        GO111MODULE=on go get -v -t
    - name: Build
      run: go build *.go 
