# .github/workflows/release.yaml

name: Release
on: release

jobs:
  release-linux-386:
      name: release linux/386
      runs-on: ubuntu-latest
      strategy:
        matrix:
          goos: [linux]
          goarch: ["386"]
      steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
      - uses: actions/checkout@master
      - name: Get dependencies
        run: |
          go mod vendor
          GOOS=linux GOARCH=386 go install github.com/tarm/serial
          GOOS=linux GOARCH=386 go install go.bug.st/serial
          GO111MODULE=on go get -v -t
        env:
          GO111MODULE: on
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GO111MODULE: on
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: "386"
          GOOS: linux
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: Get dependencies
      run: |
        go mod vendor
        GOOS=linux GOARCH=amd64 go install github.com/tarm/serial
        GOOS=linux GOARCH=amd64 go install go.bug.st/serial
        GO111MODULE=on go get -v -t
      env:
        GO111MODULE: on
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: linux
  release-darwin-386:
    name: release darwin/386
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: ["386"]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: Get dependencies
      run: |
        go mod vendor
        GOOS=darwin GOARCH=386 go install github.com/tarm/serial
        GOOS=darwin GOARCH=386 go install go.bug.st/serial
        GO111MODULE=on go get -v -t
      env:
        GO111MODULE: on
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: darwin
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: Get dependencies
      run: |
        go mod vendor
        GOOS=darwin GOARCH=amd64 go install github.com/tarm/serial
        GOOS=darwin GOARCH=amd64 go install go.bug.st/serial
        GO111MODULE=on go get -v -t
      env:
        GO111MODULE: on
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: darwin
  release-windows-386:
    name: release windows/386
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: ["386"]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: Get dependencies
      run: |
        go mod vendor
        GOOS=windows GOARCH=386 go install github.com/tarm/serial
        GOOS=windows GOARCH=386 go install go.bug.st/serial
        GO111MODULE=on go get -v -t
      env:
        GO111MODULE: on
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: windows
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: Get dependencies
      run: |
        go mod vendor
        GOOS=windows GOARCH=amd64 go install github.com/tarm/serial
        GOOS=windows GOARCH=amd64 go install go.bug.st/serial
        GO111MODULE=on go get -v -t
      env:
        GO111MODULE: on
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: windows