# .github/workflows/release.yaml

name: Release
on:
  release:
    types: 
      - created

jobs:
  release-linux-386:
      name: release linux/386
      runs-on: ubuntu-latest
      strategy:
        matrix:
          goos: [linux]
          goarch: ["386"]
      steps:
      - name: Pre Install
        run: |
          sudo apt-get install build-essential gcc
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GO111MODULE: on
          CGO_ENABLED: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: "386"
          GOOS: linux
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - name: Pre Install
      run: |
        sudo apt-get install build-essential gcc
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        CGO_ENABLED: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: linux
  release-darwin-386:
    name: release darwin/386
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: ["386"]
    steps:
    - name: Pre Install
      run: |
        sudo apt-get install -y build-essential gcc
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        CGO_ENABLED: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: darwin
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64]
    steps:
    - name: Pre Install
      run: |
        sudo apt-get install -y build-essential gcc
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        CGO_ENABLED: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: darwin
  release-windows-386:
    name: release windows/386
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: ["386"]
    steps:
    - name: Pre Install
      run: |
        sudo apt-get install -y build-essential gcc
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        CGO_ENABLED: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: windows
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
    steps:
    - name: Pre Install
      run: |
        sudo apt-get install -y build-essential gcc
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        CGO_ENABLED: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: windows