# .github/workflows/release.yaml

name: Release
on: release

jobs:
  # releases-matrix:
  #   name: Release Go Binary
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64 
  #       goos: [linux]
  #       # goos: [linux, windows, darwin]
  #       # goarch: ["386", amd64]
  #   steps:
  #     - name: Set up Go 1.x
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: ^1.14
  #       id: go
  #     - name: Check out code into the Go module directory
  #       uses: actions/checkout@v2

  #     - name: Get dependencies
  #       run: |
  #         go mod vendor
  #         go get -v -t
  #     - name: BUILD
  #       run: |
  #         chmod u+x build.sh    
  #         ./build.sh
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



  release-linux-386:
      name: release linux/386
      runs-on: ubuntu-latest
      strategy:
        matrix:
          goos: [linux]
          goarch: ["386"]
      steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
      - uses: actions/checkout@master
      - name: Get dependencies
        run: |
          go mod vendor
          go get go.bug.st/serial
          GO111MODULE=on go get -v -t
        env:
          GO111MODULE: on
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GO111MODULE: on
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: "386"
          GOOS: linux
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: Get dependencies
      run: |
        go mod vendor
        go get go.bug.st/serial
        GO111MODULE=on go get -v -t
      env:
        GO111MODULE: on
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: linux
  release-darwin-386:
    name: release darwin/386
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: ["386"]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: Get dependencies
      run: |
        go mod vendor
        go get go.bug.st/serial
        GO111MODULE=on go get -v -t
      env:
        GO111MODULE: on
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: darwin
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: Get dependencies
      run: |
        go mod vendor
        go get go.bug.st/serial
        GO111MODULE=on go get -v -t
      env:
        GO111MODULE: on
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: darwin
  release-windows-386:
    name: release windows/386
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: ["386"]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: Get dependencies
      run: |
        go mod vendor
        go get go.bug.st/serial
        GO111MODULE=on go get -v -t
      env:
        GO111MODULE: on
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: windows
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
    - uses: actions/checkout@master
    - name: Get dependencies
      run: |
        go mod vendor
        go get go.bug.st/serial
        GO111MODULE=on go get -v -t
      env:
        GO111MODULE: on
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: windows