# .github/workflows/release.yaml

name: Build
on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64 
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
    steps:
      - uses: actions/setup-go@v2.0.3
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          # go get -v -t -d ./...

          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@master
